Download:
  AriaHost: 127.0.0.1
  AriaToken: ""
  AriaRemotePath: ""
  AriaPort: 6800
  AriaSSL: false
  AriaUsername: ""
  AutoRename: true
  Concurrent: 3
  DefaultPath: true
  FullPath: true
  Path: C:/
  PrimaryEngine: Embed
  SkipViolation: true
  ThirdPartyActiveEngine: IDM
  ThirdPartyEngine: ""
Network:
  IPResolve: Auto
  Proxy: false
  ProxyEngine: None
  ProxyHost: ""
  ProxyPassword: ""
  ProxyPort: ""
  ProxyUsername: ""
Office:
  ThirdPartyEngine: ""
Other:
  CustomPassword: 3344
  Expire: Week
  LinkTemplate: "链接: %1\n提取码: %2"
  NewFolderTemplate: 「yyyy-MM-dd hh-mm-ss-zzz」
  Password: None
  ShareExpire: Week
Ui:
  ContextMenu: true
  Font: ""
  MinimizeToTray: true
  Notice: true
  Sign: true
  Theme: Dark
  TrayIcon: true
Upload:
  Concurrent: 3
  Filter:
    - desktop.ini
  SkipNoRapid: false
Video:
  Quality: Origin
  Stream: Live
  ThirdPartyActiveEngine: VLC
  ThirdPartyEngine: ""
  UseOrigin: true
  UseSub: true